version: 2.1

<<<<<<< HEAD
jobs:
  build:
    docker:
      - image: alpine:3.9
    working_directory: /project
    environment:
      VERSION: bootstrap
      ESPBUILD_VERSION: 0.01
      GHR_VERSION: v0.12.1
    steps:
      - run: apk add ca-certificates curl git go build-base
=======
executors:
  esplinux-bootstrap:
    docker:
      - image: esplinux/bootstrap
    environment:
      VERSION: "0.01"

jobs:
  libarchive:
    executor: esplinux-bootstrap
    steps:
>>>>>>> a466906ee14a7bfeca32e30bc69e5be72b45cc05
      - checkout
      - run:
          name: Build
          shell: /bin/sh -e
          command: |
<<<<<<< HEAD
            curl -LO https://github.com/esplinux/espbuild/releases/download/$ESPBUILD_VERSION/espbuild-static.tar.gz
            tar xf espbuild-static.tar.gz
            bin/espbuild ${CIRCLE_PROJECT_REPONAME}.conf
            go mod init .
            go get github.com/tcnksm/ghr@$GHR_VERSION
            ~/go/bin/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /package
=======
            esp add ghr espbuild
            echo gnu >> /etc/esp-repos
            espbuild libarchive.conf
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package
>>>>>>> a466906ee14a7bfeca32e30bc69e5be72b45cc05

workflows:
  version: 2
  build:
    jobs:
<<<<<<< HEAD
      - build
=======
      - libarchive
>>>>>>> a466906ee14a7bfeca32e30bc69e5be72b45cc05
