version: 2.1

jobs:
  build:
    docker:
      - image: esplinux/bootstrap
    working_directory: /project
    environment:
      VERSION: "0.01"
      ESPBUILD_VERSION: "0.01"
      GHR_VERSION: "v0.12.1"
    steps:
      - run: esp add ghr espbuild
      - checkout
      - run:
          name: Build
          command: |
            espbuild ${CIRCLE_PROJECT_REPONAME}.conf
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /package

workflows:
  version: 2
  build:
    jobs:
      - build
